<?php

/**
 * @file
 * Contains custom_mutt_world.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function custom_mutt_world_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_mutt_world module.
    case 'help.page.custom_mutt_world':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom coding for all the mutts') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_mutt_world_theme() {
  return [
    'custom_mutt_world' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_entity_type_alter().
 */
function custom_mutt_world_entity_type_alter(array &$entity_types) {
  //attach our form class
  $entity_types['node']->setFormClass('default', 'Drupal\custom_mutt_world\Form\MuttForm');
}

function afc_crm_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  //the form id we are targeting for use in the mutts
  $mutt_form_id = 'node_mutts_form';

  //if ($form_id == $mutts_form_id) {
  //  $user = User::load(\Drupal::currentUser()->id());
  //  $access = $user->hasPermission('access crm');

  //  $form['field_assign_to_department']['#access'] = $access;
  //  $form['field_comments']['#access'] = $access;
  //  $form['field_request_type']['#access'] = $access;
  //  $form['field_status']['#access'] = $access;
  //  $form['revision_log']['#access'] = $access;
  //  $form['field_urgent']['#access'] = $access;
  //  $form['field_manager_email_sent']['#access'] = $access;
//  }
}
